import urllib.request
import json
import datetime
import random
import string
import time
import os
import sys
import multiprocessing

os.system("title WARP-PLUS-CLOUDFLARE By ALIILAPRO")
os.system('cls' if os.name == 'nt' else 'clear')
print('Getting WARP+ Traffic on Github Actions')
referrer = "c8c65ab5-2c9f-42de-ad94-64ab73531cbe"
def genString(stringLength):
	try:
		letters = string.ascii_letters + string.digits
		return ''.join(random.choice(letters) for i in range(stringLength))
	except Exception as error:
		print(error)		    
def digitString(stringLength):
	try:
		digit = string.digits
		return ''.join((random.choice(digit) for i in range(stringLength)))    
	except Exception as error:
		print(error)	
url = f'https://api.cloudflareclient.com/v0a{digitString(3)}/reg'
def run():
	try:
		install_id = genString(22)
		body = {"key": "{}=".format(genString(43)),
				"install_id": install_id,
				"fcm_token": "{}:APA91b{}".format(install_id, genString(134)),
				"referrer": referrer,
				"warp_enabled": False,
				"tos": datetime.datetime.now().isoformat()[:-3] + "+02:00",
				"type": "Android",
				"locale": "es_ES"}
		data = json.dumps(body).encode('utf8')
		headers = {'Content-Type': 'application/json; charset=UTF-8',
					'Host': 'api.cloudflareclient.com',
					'Connection': 'Keep-Alive',
					'Accept-Encoding': 'gzip',
					'User-Agent': 'okhttp/3.12.1'
					}
		req         = urllib.request.Request(url, data, headers)
		response    = urllib.request.urlopen(req)
		status_code = response.getcode()	
		return status_code
	except Exception as error:
		print(error)	
def start():
	g = 0
	b = 0
	while True:
		result = run()
		if result == 200:
			g = g + 1
			os.system('cls' if os.name == 'nt' else 'clear')
			print("")
			print("Getting WARP+ Traffic")
			print("")
			print(f"\n[-] WORK ON ID: {referrer}")    
			print(f"[:)] {g} GB has been successfully added to your account.")
			print(f"[#] Total: {g} Good {b} Bad")
			print("[*] After 5 seconds, a new request will be sent.")
			time.sleep(15)
		else:
			b = b + 1
			os.system('cls' if os.name == 'nt' else 'clear')
			print("")
			print("Getting WARP+ Traffic")
			print("")
			print("[:(] Error when connecting to server.")
			print(f"[#] Total: {g} Good {b} Bad")	

p0 = multiprocessing.Process(target=start)
p0.start()
p0.join()
time.sleep(1)
p1 = multiprocessing.Process(target=start)
p1.start()
p1.join()
time.sleep(1)
p2 = multiprocessing.Process(target=start)
p2.start()
p2.join()
time.sleep(1)
p3 = multiprocessing.Process(target=start)
p3.start()
p3.join()
time.sleep(1)
p4 = multiprocessing.Process(target=start)
p4.start()
p4.join()
time.sleep(1)
p5 = multiprocessing.Process(target=start)
p5.start()
p5.join()
time.sleep(1)
p6 = multiprocessing.Process(target=start)
p6.start()
p6.join()
time.sleep(1)
p7 = multiprocessing.Process(target=start)
p7.start()
p7.join()
time.sleep(1)
p8 = multiprocessing.Process(target=start)
p8.start()
p8.join()
time.sleep(1)
p9 = multiprocessing.Process(target=start)
p9.start()
p9.join()
time.sleep(1)
p10 = multiprocessing.Process(target=start)
p10.start()
p10.join()
time.sleep(1)
p11 = multiprocessing.Process(target=start)
p11.start()
p11.join()
time.sleep(1)
p12 = multiprocessing.Process(target=start)
p12.start()
p12.join()
time.sleep(1)
p13 = multiprocessing.Process(target=start)
p13.start()
p13.join()
time.sleep(1)
p14 = multiprocessing.Process(target=start)
p14.start()
p14.join()
time.sleep(1)
p15 = multiprocessing.Process(target=start)
p15.start()
p15.join()
time.sleep(1)
p16 = multiprocessing.Process(target=start)
p16.start()
p16.join()
time.sleep(1)
p17 = multiprocessing.Process(target=start)
p17.start()
p17.join()
time.sleep(1)
p18 = multiprocessing.Process(target=start)
p18.start()
p18.join()
time.sleep(1)
p19 = multiprocessing.Process(target=start)
p19.start()
p19.join()
time.sleep(1)
p20 = multiprocessing.Process(target=start)
p20.start()
p20.join()
time.sleep(1)
p21 = multiprocessing.Process(target=start)
p21.start()
p21.join()
time.sleep(1)
p22 = multiprocessing.Process(target=start)
p22.start()
p22.join()
time.sleep(1)
p23 = multiprocessing.Process(target=start)
p23.start()
p23.join()
time.sleep(1)
p24 = multiprocessing.Process(target=start)
p24.start()
p24.join()
time.sleep(1)
p25 = multiprocessing.Process(target=start)
p25.start()
p25.join()
time.sleep(1)
p26 = multiprocessing.Process(target=start)
p26.start()
p26.join()
time.sleep(1)
p27 = multiprocessing.Process(target=start)
p27.start()
p27.join()
time.sleep(1)
p28 = multiprocessing.Process(target=start)
p28.start()
p28.join()
time.sleep(1)
p29 = multiprocessing.Process(target=start)
p29.start()
p29.join()
time.sleep(1)
p30 = multiprocessing.Process(target=start)
p30.start()
p30.join()
time.sleep(1)
p31 = multiprocessing.Process(target=start)
p31.start()
p31.join()
time.sleep(1)
p32 = multiprocessing.Process(target=start)
p32.start()
p32.join()
time.sleep(1)
p33 = multiprocessing.Process(target=start)
p33.start()
p33.join()
time.sleep(1)
p34 = multiprocessing.Process(target=start)
p34.start()
p34.join()
time.sleep(1)
p35 = multiprocessing.Process(target=start)
p35.start()
p35.join()
time.sleep(1)
p36 = multiprocessing.Process(target=start)
p36.start()
p36.join()
time.sleep(1)
p37 = multiprocessing.Process(target=start)
p37.start()
p37.join()
time.sleep(1)
p38 = multiprocessing.Process(target=start)
p38.start()
p38.join()
time.sleep(1)
p39 = multiprocessing.Process(target=start)
p39.start()
p39.join()
time.sleep(1)
p40 = multiprocessing.Process(target=start)
p40.start()
p40.join()
time.sleep(1)
p41 = multiprocessing.Process(target=start)
p41.start()
p41.join()
time.sleep(1)
p42 = multiprocessing.Process(target=start)
p42.start()
p42.join()
time.sleep(1)
p43 = multiprocessing.Process(target=start)
p43.start()
p43.join()
time.sleep(1)
p44 = multiprocessing.Process(target=start)
p44.start()
p44.join()
time.sleep(1)
p45 = multiprocessing.Process(target=start)
p45.start()
p45.join()
time.sleep(1)
p46 = multiprocessing.Process(target=start)
p46.start()
p46.join()
time.sleep(1)
p47 = multiprocessing.Process(target=start)
p47.start()
p47.join()
time.sleep(1)
p48 = multiprocessing.Process(target=start)
p48.start()
p48.join()
time.sleep(1)
p49 = multiprocessing.Process(target=start)
p49.start()
p49.join()
time.sleep(1)
p50 = multiprocessing.Process(target=start)
p50.start()
p50.join()
time.sleep(1)
p51 = multiprocessing.Process(target=start)
p51.start()
p51.join()
time.sleep(1)
p52 = multiprocessing.Process(target=start)
p52.start()
p52.join()
time.sleep(1)
p53 = multiprocessing.Process(target=start)
p53.start()
p53.join()
time.sleep(1)
p54 = multiprocessing.Process(target=start)
p54.start()
p54.join()
time.sleep(1)
p55 = multiprocessing.Process(target=start)
p55.start()
p55.join()
time.sleep(1)
p56 = multiprocessing.Process(target=start)
p56.start()
p56.join()
time.sleep(1)
p57 = multiprocessing.Process(target=start)
p57.start()
p57.join()
time.sleep(1)
p58 = multiprocessing.Process(target=start)
p58.start()
p58.join()
time.sleep(1)
p59 = multiprocessing.Process(target=start)
p59.start()
p59.join()
time.sleep(1)
p60 = multiprocessing.Process(target=start)
p60.start()
p60.join()
time.sleep(1)
p61 = multiprocessing.Process(target=start)
p61.start()
p61.join()
time.sleep(1)
p62 = multiprocessing.Process(target=start)
p62.start()
p62.join()
time.sleep(1)
p63 = multiprocessing.Process(target=start)
p63.start()
p63.join()
time.sleep(1)
p64 = multiprocessing.Process(target=start)
p64.start()
p64.join()
time.sleep(1)
p65 = multiprocessing.Process(target=start)
p65.start()
p65.join()
time.sleep(1)
p66 = multiprocessing.Process(target=start)
p66.start()
p66.join()
time.sleep(1)
p67 = multiprocessing.Process(target=start)
p67.start()
p67.join()
time.sleep(1)
p68 = multiprocessing.Process(target=start)
p68.start()
p68.join()
time.sleep(1)
p69 = multiprocessing.Process(target=start)
p69.start()
p69.join()
time.sleep(1)
p70 = multiprocessing.Process(target=start)
p70.start()
p70.join()
time.sleep(1)
p71 = multiprocessing.Process(target=start)
p71.start()
p71.join()
time.sleep(1)
p72 = multiprocessing.Process(target=start)
p72.start()
p72.join()
time.sleep(1)
p73 = multiprocessing.Process(target=start)
p73.start()
p73.join()
time.sleep(1)
p74 = multiprocessing.Process(target=start)
p74.start()
p74.join()
time.sleep(1)
p75 = multiprocessing.Process(target=start)
p75.start()
p75.join()
time.sleep(1)
p76 = multiprocessing.Process(target=start)
p76.start()
p76.join()
time.sleep(1)
p77 = multiprocessing.Process(target=start)
p77.start()
p77.join()
time.sleep(1)
p78 = multiprocessing.Process(target=start)
p78.start()
p78.join()
time.sleep(1)
p79 = multiprocessing.Process(target=start)
p79.start()
p79.join()
time.sleep(1)
p80 = multiprocessing.Process(target=start)
p80.start()
p80.join()
time.sleep(1)
p81 = multiprocessing.Process(target=start)
p81.start()
p81.join()
time.sleep(1)
p82 = multiprocessing.Process(target=start)
p82.start()
p82.join()
time.sleep(1)
p83 = multiprocessing.Process(target=start)
p83.start()
p83.join()
time.sleep(1)
p84 = multiprocessing.Process(target=start)
p84.start()
p84.join()
time.sleep(1)
p85 = multiprocessing.Process(target=start)
p85.start()
p85.join()
time.sleep(1)
p86 = multiprocessing.Process(target=start)
p86.start()
p86.join()
time.sleep(1)
p87 = multiprocessing.Process(target=start)
p87.start()
p87.join()
time.sleep(1)
p88 = multiprocessing.Process(target=start)
p88.start()
p88.join()
time.sleep(1)
p89 = multiprocessing.Process(target=start)
p89.start()
p89.join()
time.sleep(1)
p90 = multiprocessing.Process(target=start)
p90.start()
p90.join()
time.sleep(1)
p91 = multiprocessing.Process(target=start)
p91.start()
p91.join()
time.sleep(1)
p92 = multiprocessing.Process(target=start)
p92.start()
p92.join()
time.sleep(1)
p93 = multiprocessing.Process(target=start)
p93.start()
p93.join()
time.sleep(1)
p94 = multiprocessing.Process(target=start)
p94.start()
p94.join()
time.sleep(1)
p95 = multiprocessing.Process(target=start)
p95.start()
p95.join()
time.sleep(1)
p96 = multiprocessing.Process(target=start)
p96.start()
p96.join()
time.sleep(1)
p97 = multiprocessing.Process(target=start)
p97.start()
p97.join()
time.sleep(1)
p98 = multiprocessing.Process(target=start)
p98.start()
p98.join()
time.sleep(1)
p99 = multiprocessing.Process(target=start)
p99.start()
p99.join()
time.sleep(1)
	
